### ISSUE TITLE
Question: Trusted Players

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#103]
I see we only do not use the isAdmin flag, do you want the canAddTrustedPlayers flag to also count as being able to change permissions and drop the turret etc?

**Comment by Poenjabiesous** [comment]
Hmmm... I don't think we should allow anyone besides the owner to be able to drop bases/turrets. Otherwise, if another trusted player can drop it, he can pick it up and place them again, making him the owner. The permissions system should allow other players to access certain turret base functionality, not own it.

**Comment by Keridos** [comment]
That is why I had the isAdmin flag, I personally have people I trust enough to give them full access.

**Comment by Poenjabiesous** [comment]
Then lets give that perm to players that can dd other trusted players.

**Comment by Keridos** [comment]
Ok.
