### ISSUE TITLE
Feature Request: Amor Piercing/HP Percentage Damage

### ISSUE THREAD

**Issue by lellasone** [OpenModularTurretsTeam/OpenModularTurrets#168]
Having some way to add armor piercing damage, perhaps in the form of an upgrade or special turret (or even config setting) would greatly expand end game utility. 

There is currently no good way to defend bases from end game armor players (Short of the "I win button" type blocks) so having a more dynamic mechanic for doing that would be really wonderful

**Comment by Poenjabiesous** [comment]
I'm not sure if I agree with this, as there are already a lot of tools (and a turret - Railgun) that will increase a turrets' damage output to a point where armor doesn't really matter anymore.

**Comment by Keridos** [comment]
The Railgun *should* have a 100% armor pen shot already. If there is any armor out there that prevents that, tell us here please, I will then *fix* that.

**Comment by AnodyneEntity** [comment]
Draconic Evolution Draconic Armor.

http://minecraft.curseforge.com/mc-mods/223565-draconic-evolution

**Comment by Keridos** [comment]
Oki, I will put the super evil armor pen code in then. Simply just remove the specified damage from the targets life pool. @Poenjabiesous you happen to know if that will automatically kill the target if the HP drops below 0?

**Comment by lellasone** [comment]
Maybe not for the full damage of the railgun? It’s current mechanics against other advanced armors (multiple hits to deplete quantum then a kill) are really awesome.

**Comment by Keridos** [comment]
The problem there is that I need to find out where to draw the line. Maybe I will add in compatibility for the armors that completely block damage even if it is a bit more work. Just need to figure out on how to get info about the armor preferably without having to compile this mod against every mod that adds those armors.

**Comment by Poenjabiesous** [comment]
I agree @Keridos, we will need to draw the line somewhere. I think that this specific instance of armor from Draconic Evolution may do something like override the event when the entity that is wearing it gets damaged, (or something similar) and then handles the actual damage values internally. Directly deducting health points may be a good workaround, but we will need to confirm through testing.

**Comment by AnodyneEntity** [comment]
@Keridos Draconic Evolution's armor doesn't block damage, it just adds additional life to the persons total life people based on how much energy you're holding. It's why armor penetration doesn't work on it as tested with both the Railgun and the Tinkers' Construct Rapier. What would be cool is if you could make it take out a percentage of the persons health instead of just a flat rate, that way it completely nullifies armors that simply extend life pools instead of just being more resistant to damage.

**Comment by Poenjabiesous** [comment]
@AnodyneEntity

Thanks for the info. I have personally never played with the mod, so I had no idea on the mechanics involved.

Yes, it seems like a good idea to then add a health pool percentage damage increase (15% - 20%) to the railgun turret (or all turrets that has armor pen?), and a flat rate damage decrease (minus 3 to 5 points).

Use cases that would make this plausible:

1. A player with 50 health points gets shot by the Railgun turret. As per standard config, the player should then have 32 health points left (since armor is ignored). 

With this new change, if the same player with 50 health points gets shot, he should have: 

50 - (18 - 3) - (50 * 0.15) = 28.5 life points left.

With 100 life points:

100 - (18 -3) - (100 * 0.15) = 70 life points left.

This change will make the turrets much more effective against late-game players.

**Comment by Keridos** [comment]
This seems to be a good solution. We need to check though if there are armors blocking neutral damage (which is the one penetrating armor in vanilla MC). As far as I remember I read that Draconic Evolution Armor does this as well.

**Comment by AnodyneEntity** [comment]
@Keridos Perhaps something like this;

Railgun Turret - 50% HP per hit.
Missle Turret - 25% HP per hit
Grenade Turret - 10% HP per hit
Machine Gun Turret - 5% HP per hit

Not sure if it's possible to calculate this, but if it is, possibly make it so that every pellet from the Shotgun Turret does 1-2% HP. This'll make it lethal at close range like it should, but moderately lethal at medium range.
