### ISSUE TITLE
Turrets shooting at nothing

### ISSUE THREAD

**Issue by PolymerBoy** [OpenModularTurretsTeam/OpenModularTurrets#172]
I am playing on a super flat world on a modpack that I made. Suddenly, a while after the world is created, the turrets start shooting at nothing. At first, it was at ground level, but it steadily went upwards.

I do have EvilCraft installed, but it is not due to vengeance spirits.

**Comment by Keridos** [comment]
Does not happen for me in SSP with OMT alone, It most likely is some other mod derping up

**Comment by Poenjabiesous** [comment]
Also tested and could not reproduce the results. I agree with @Keridos, this happens because of an external factor. A turret (according to the code) will only attack when the following criteria are met:

1. There's an entity (of type IMob, EntityPlayer, EntityAnimal or EntityAmbient) in range.
2. The turret has LOS to the entity.
3. The turret has ammo/power.
4. The turret is set up to attack the entity type, and the entity is not a player entity that is in creative mode, or a trusted player.

Thus, something is spawning an invisible entity that meets the above criteria.

I am closing this ticket, but I will keep an eye out for anything that might point to this being an issue.

Thanks for the feedback.

**Comment by PolymerBoy** [comment]
I found the issue in the end. Orespawn put crickets inside of Mekanism energy cells and the turrets were trying to hit them inside the block.
