### ISSUE TITLE
Relativistic Turret culls block face below it

### ISSUE THREAD

**Issue by HanFox** [OpenModularTurretsTeam/OpenModularTurrets#178]
I think the subject line says it all.

Using v2.1.5: http://puu.sh/kRYi8/422001fb30.png

**Comment by Poenjabiesous** [comment]
Now that's interesting. Thanks, will have a look at it.

**Comment by Poenjabiesous** [comment]
After several attempts and different permutations, I am unable to recreate the issue.

![cullingresponse](https://cloud.githubusercontent.com/assets/8829214/11016261/5f153d76-8584-11e5-9d72-b487cda6641a.jpg)

**Comment by HanFox** [comment]
Really? That's odd because I can't do anything but cause it to cull. I even removed every other mod from my test instance (which was just CoFH and NEI and IGW) and it still does it.

Is it a Forge issue? What version of Forge do you actually recommend so I can check? I'm using 1448 currently.

**Comment by Poenjabiesous** [comment]
This seems to be an edge case that is dependent on environmental specifics. Unfortunately, due to the nature of development, if I am unable to recreate the issue,I don't know what to fix. If you can point out the exact block of code that you think is causing this, I can investigate further. But as you can see from the above testing snippet, I am unable to recreate the issue, so I cant pinpoint what is going wrong in your environment.

**Comment by HanFox** [comment]
I actually figured this out just arbitrarily... it's related to Smooth Lighting.

If you turn Smooth Lighting off the block will cull otherwise on Min or Max it's fine.
