### ISSUE TITLE
On server, cannot break, or modify users in turret base

### ISSUE THREAD

**Issue by badtzmaru** [OpenModularTurretsTeam/OpenModularTurrets#180]
I have used this mod in the past and know how it works completely. The problem is that I run my server in offline mode, so that if the mojang auth servers are down we can continue to play. I think that this would break some of the features of the turrets because the server does not know each player's uuids.

**Comment by Poenjabiesous** [comment]
As per #162:

"The thing is that we would need to make the entire UUID system compatible with offline mode. Second thing is that I think 99,9% of the people who use offline mode make it to make cracked clients possible to join their server and me and @Poenjabiesous have agreed that we will NOT make this mod compatible with cracked clients."

We cannot enforce/help people playing offline/cracked servers. If the users are all premium, an online server would not be an issue- Mojang auth servers have an uptime of 99.9%, so purely creating an offline server for that reason is not a good one in my opinion.

Thirdly, please check old tickets in the future before opening up a new one, this topic has been actively discussed in at least 5 previous tickets.
