### ISSUE TITLE
Turret bases not dropping when punched

### ISSUE THREAD

**Issue by Loggerc4** [OpenModularTurretsTeam/OpenModularTurrets#194]
This issue is on multiplayer, 1.7.10, forge 10.13.2.1291
Mod version: 2.1.5-184
Using Mekanism 7.1.0.92 as recipe mod.

When someone punches a turret base, including other people's turret bases, it will break instantly and not drop the base, only the attachments, ammo, upgrades, turret, etc.
This happens for all base tiers, and is a large problem on PvP servers. 
Also, I'm sorry if we just need to update the turret mod itself or if this is fixed.
Thanks, -Logg

**Comment by Poenjabiesous** [comment]
This is not a bug, you probably enabled the config option:

miscellaneous {
    B:"Are turrets/turret bases breakable by anyone?"=true

in the config file. The bases don't drop because on a PvP server where everyone can break everyone's bases, someone will be able to pick up the dropped base and re-place it, making him become the owner.

Please make sure in the future that the tickets you create are bugs, and not just something that precedes one's own preconception on how the mod should work.
