### ISSUE TITLE
(Feature) Add force rotate and shoot metods for CC

### ISSUE THREAD

**Issue by Ksnz** [OpenModularTurretsTeam/OpenModularTurrets#198]
It would be great if  turret can target not only living entities

**Comment by Keridos** [comment]
Turrets should fire at ghast fireballs and arrows or what do you want to accomplish for this? And is the force rotate and shoot just for doing fancy shooting without targets?

**Comment by Ksnz** [comment]
Just for doing fancy shooting.
I have WarpDrive mod on my server and with this feature turrets can also be used for destroying enemy  ships or cleaning path in front of ship from asteroids.
Sorry for my bad english :tired_face:

**Comment by Poenjabiesous** [comment]
As a user, what methods do you expect to see?

**Comment by Ksnz** [comment]
Smth like setYaw setPitch (optional- targetAt(x,y,z)) and shoot

**Comment by Keridos** [comment]
I think we should just add targetAt(x,y,z) and shoot, more should not be needed. Also add in a cooldown for the shooting of course.

**Comment by shadoxxhd** [comment]
there should be a loopFire() command which makes the turret fire until instructed otherwise. also, it would be nice to have a way to make the turret stop searching for targets on its own while controlling it (otherwise it might be on cooldown when you need it)

would it be possible to set the grenade turret to different fire angels via CC? you could use a flatter arc inside of buildings or a higher arc to fire over a wall

**Comment by Keridos** [comment]
You can already turn off targeting via CC/OC commands. If needed we can add in a command like rotate(yaw,pitch).

**Comment by Keridos** [comment]
This is a bit more tricky than I expected. Gonna take a bit longer to implement.
