### ISSUE TITLE
[feature] spread fire mode/ targeting mode/ target selection

### ISSUE THREAD

**Issue by shadoxxhd** [OpenModularTurretsTeam/OpenModularTurrets#201]
*spread fire*: can be toggled in base configuration. turret switches target after every shot (either random or the entity which hasn't been hit for the longest time). good for suppression fire etc. 

*targeting mode*: prioritizes targets based on setting: none ('old' targeting behavior), near, far, high health, low health, high max health, low max health, ... (available options could be toggled in the config). <br>in focused mode this kicks in when the current target dies. in scatter mode it re-checks its target after every shot (useful eg. for a laser if you have a grenade turret which then can AoE low health enemies more effectively))

*target selection*: target-only-in-box (eg. for making a safe path through turret-monitored terrain), only >50% HP (for scaring players away or flagging them for a <50% turret), only <50% HP, only >10 blocks distance (eg. useful for teleporters), certain mob types only, ... <br>
this could be implemented as a upgrade card with its own GUI

**Comment by Poenjabiesous** [comment]
1. Spread Fire: There's already a multi-target function in the turret base that forces each turret on the base to fire at individual targets. What is described here is too much like the already existing functionality.

2. Targeting mode: This I do agree with, but will probably only be implemented in the 1.8 versions of the game. No new functionality or development (except very serious issues) will be fixed in the 1.7.10 version at this time.

3. Same as above.

**Comment by shadoxxhd** [comment]
the spread targeting is to prevent high health/rapid regen/invulnerable entities to prevent the turret from killing 'normal' enemies in range
