### ISSUE TITLE
Bug regarding the camouflage of turret bases

### ISSUE THREAD

**Issue by Gregorsharpe** [OpenModularTurretsTeam/OpenModularTurrets#209]
Forge 10.13.4.1558
Minecraft 1.7.10

Loaded Mods: NEI, Buildcraft, Computercraft, Industrialcraft2 (experimental), OpenCCSensors, Power Converters and Open Modular Turrets.

When right-clicking a turret base with a solid block (tested with dirt, grass, cobble, sand and wood planks) the block is not applied as camo. The user also doesn't gain access to the turret as specified in OMT v2.1.0, so it doesn't seem to be a version issue.

**Comment by Poenjabiesous** [comment]
Is this happening on an offline server?

**Comment by Gregorsharpe** [comment]
No, this is taking place on a small multiplayer server of ~6 players.

On Mon, Mar 14, 2016 at 8:27 AM, Poenjabiesous < notifications@github.com [notifications@github.com] > wrote:
Is this happening on an offline server?

—
Reply to this email directly or view it on GitHub
[https://github.com/OpenModularTurretsTeam/OpenModularTurrets/issues/209#issuecomment-196289763] .[https://github.com/notifications/beacon/AHNX4KymFragZFkj0GVTysCLG_PL_vdLks5ptVQjgaJpZM4Hu1FU.gif]

**Comment by Gregorsharpe** [comment]
We're currently running OMT 2.1.9-211. I only included v2.1.0 in the ticket as a reference to the version this functionality was added.

**Comment by Poenjabiesous** [comment]
I mean, in server.properties, is the server set to offline mode?

**Comment by Gregorsharpe** [comment]
No, the server's online-mode is set to true.

**Comment by Poenjabiesous** [comment]
The reason for this happening, is because the server is unable to retrieve the UUID's for the players placing the turret bases (Whatever may be causing this), and is usually the result of offline servers, cracked clients/servers (non-premium users) and servers that don't have internet access. This is related to a number of previous tickets, and due to the fact that we do not support any activity relating to offline/cracked servers, I can merely direct you to previous tickets relating to this.

If the server and clients are official with premium account used, and the server has internet access, OMT works.

See:
https://github.com/OpenModularTurretsTeam/OpenModularTurrets/issues/180
https://github.com/OpenModularTurretsTeam/OpenModularTurrets/issues/174
https://github.com/OpenModularTurretsTeam/OpenModularTurrets/issues/135
