### ISSUE TITLE
Turret tooltips should say the real accuracy rather than "low", "medium", etc...

### ISSUE THREAD

**Issue by UntouchedWagons** [OpenModularTurretsTeam/OpenModularTurrets#21]
It's not clear what "low", "medium", etc... means, plus those words are hard coded into the ItemBlock's addInformation method.

Additionally, the accuracy in the config should be a value measured in percentages. In the game Borderlands, a gun with 98% accuracy means the bullet can deviate up to 1 unit every 100 units of travel. Right now in the config accuracy is stored as something like 1, 3 and 5 which means next to nothing. I don't know how accuracy works in the code but the config should present accuracy as a percentage.

**Comment by Poenjabiesous** [comment]
The accuracy system that minecraft uses, is a float value that gets passed while setting a projectiles' heading, where 0.0F is no deviation whatsoever. 

I propose this:

1. A maximum deviation float of 10.0F (T1 turrets use 5.0F)
2. config expression will then change to a value between 0 - 100, to an inverted float value, where 0 = 10.0F and 100 = 0.0F

Based on my testing over a turret-to-target-distance of 10 blocks, the hit ratio seems to be exactly that what we would expect it to be, with 10 shots fired.

FLOAT|HIT RATE

1. 10.0F|1/10
2. 9.0F|1/10
3. 8.0F|3/10
4. 7.0F|2/10
5. 6.0F|4/10
6. 5.0F|6/10
7. 4.0F|6/10
8. 3.0F|7/10
9. 2.0F|9/10
10. 1.0F|10/10
11. 0.0F|10/10

Since the test sample is very small I can't calculate standard deviation to see if it would be statistically negligible. But based on this, at least, the expected hit rate seems to map to the ones experienced in the short test.

Happiness?

**Comment by Keridos** [comment]
Yes, this is good, just note in the config file that this is the hitrate at 10 meters. (You can add comments to the configs)
