### ISSUE TITLE
Cannot Camouflage Turret Bases

### ISSUE THREAD

**Issue by SephirothWS** [OpenModularTurretsTeam/OpenModularTurrets#211]
Running OpenModularTurrets1.7.10-2.1.9-211.jar on MinecraftForge 10.13.4.1614 with an online-mode server. My Minecraft account is premium, and the server requires a premium account to connect. I have the ability to configure the turrets I've placed, but I cannot for the life of me, apply a camouflage block to the bases.

**Comment by Gregorsharpe** [comment]
I've had the exact same issue for a couple weeks now, love to see some resolution on this. My ticket (#209) was closed because the author believed my server was running in offline mode, even though all players could place turrets that were bound exclusively to them.

**Comment by TheGameAce** [comment]
I had a while back wondered if that was a feature for the mod, checked the page and it said it was, and then attempted it in-game. Same issue. When I right click with any block to try and camouflage it, it doesn't do a thing. This is quite a frustrating issue, especially considering I'm wanting to use this in multiplayer for a private server, and it doesn't help if players can see the turret base.
Sure, mobs can be fooled because they aren't programmed to notice a turret base, but I would love to see this issue fixed ASAP.

**Comment by Poenjabiesous** [comment]
It is statements like 'but I would love to see this issue fixed ASAP' that really makes one question why one would put in personal time and effort to give freely to a community that harbors feelings like the one stated.

1. We do this in our own, personal free time. We do not get paid for doing this.

2. We do this out of the goodness of our hearts to ensure that you can have a fun and adventurous  MC experience.

3. The mod is open-source, so if you 'would love to see this issue fixed ASAP', clone the project and help us get the issues fixed, instead of telling us how much the issue frustrates you.
