### ISSUE TITLE
IC2 EU buffer saving broken

### ISSUE THREAD

**Issue by kubastick** [OpenModularTurretsTeam/OpenModularTurrets#451]
![zrzut ekranu 2018-11-28 o 19 15 07](https://user-images.githubusercontent.com/25605091/49338381-a99fab00-f620-11e8-97f3-c092b840df35.png)
Related mod list:
omlib-1.12.2-3.0.1-162
openmodularturrets-1.12.2-3.0.1-264
industrialcraft-2-2.8.104-ex112

**Comment by noituri** [comment]
Same issue

**Comment by Keridos** [comment]
What does enforced mean in this context?

**Comment by Keridos** [comment]
Interesting, probably some change in ic2 api? anyway the eu buffer is really not designed to be hard capped.
It stops requesting energy as soon as the cap is reached but apparently sometimes it gets more energy than it asks for.

**Comment by Keridos** [comment]
The formatting is not correct though, I think I never designed it to have a hard cap.
I will just remove the /7500 from the text as it is misleading.

**Comment by kubastick** [comment]
However, I think that a much better idea will be adding hard cap.
Currently, players must use the splitter cable to stop turret draining EU infinitely from generators/batbox.

**Comment by Keridos** [comment]
it should not even drain any power after it hits the soft cap.

Hard cap actually is pretty ugly to do, it means I have to send power back into the cables as far as I know.

https://github.com/OpenModularTurretsTeam/OMLib/blob/1.12/src/main/java/omtteam/omlib/tileentity/TileEntityElectric.java#L186-L206
The soft cap actually is 80k EU

**Comment by Keridos** [comment]
Well found a bug that was causing the soft cap to be partially ignored, just up to 80k EU. This is a very minor issue only and mostly affects the GUI of the base. Fix is ready. But I have not found any issues other than that. Since that code is a bit older it should not be the case that any base continously drains power. Maybe someone was a bit impatient while watching the energy transfer.
