### ISSUE TITLE
Crash when targettting strange things or render.

### ISSUE THREAD

**Issue by SirAron111** [OpenModularTurretsTeam/OpenModularTurrets#513]
https://pastebin.com/4dSaNMW3 Seems like turrets can cause a crash when they target strange things. (i wonder why they can target things like blood scent but not the primitive mobs mod mobs.) Is there a way to simply add a whitelist on what they are allowed to attack via config and turn of the feature of attacking players? (which disables these gui options in game as well) with a white list one could just put in all entities they should be allowed to attack in a modpack and that’s good for pack makers like me also solves the problem of them not finding the primitive mob mobs if they simply attack by ID not by creature type since the primitive mob mobs count as a special creature type that isn’t hostile or passive etc. so like a list with minecraft:zombie to add to manually etc

**Comment by Keridos** [comment]
This has nothing to do with targeting anything. It crashes because apparently there is some issue where an expander and a solar panel from enderio are in the same blockpos.
/edit: I might be able to help but please do use the template. it really helps me to track down bugs. But if you simply delete it and just post a crashlog with some rambling about what mightve happened is no good for me.

**Comment by SirAron111** [comment]
Will remember that sry about it! I fast forwarded the issue link here to the one who provided the crash log maybe they have more insight on their issue. Than me!

**Comment by Keridos** [comment]
see #516
